### ISSUE TITLE
abs not recognized in quadratic formula

### ISSUE THREAD

**Issue by wdkrnls** [r-cas/ryacas#48]
Trying to reproduce the solutions to the quadratic formula reveals what appears to be a bug in `yac_expr`.

```
"Solve(a^2 + b^2 == c^2, b)" %>%
  yac_str() %>%
  yac_expr()
```
For me this returns:

> expression(c(b == sqrt(fabs(a^2 - c^2)) * complex(1, cos(Arg(c^2 - 
>     a^2)/2), sin(Arg(c^2 - a^2)/2)), b == sqrt(fabs(a^2 - c^2)) * 
>     complex(1, cos((Arg(c^2 - a^2) + 2 * pi)/2), sin((Arg(c^2 - 
>         a^2) + 2 * pi)/2))))

`fabs` is not an R function in any of the packages I have installed. In other words, `??fabs` produces 'No results found' for me. Surely this should be recognized as `abs`?

**Comment by grzegorzmazur** [comment]
Hi,

I've fixed RForm() to translate Abs() to abs() instead of fabs() in https://github.com/grzegorzmazur/yacas/commit/2bd9e336200ded6fe0f079215e21e42761422e01

Please note that you have to wait until Mike pulls it over to ryacas for the fix to actually work.

Cheers,
Grzesiek

**Comment by mikldk** [comment]
Thanks for reporting this, @wdkrnls -- and sorry about the delay!

Thanks @grzegorzmazur for fixing it. I have now updated the development version of Ryacas (here at Github) with the fix in commit c9cac35.

Note that you can remove the variable names with `y_rmvars()` as shown below:

```r
> cmd <- "Solve(a^2 + b^2 == c^2, b)"
> e <- cmd %>% y_rmvars() %>% yac_expr()
> e
expression(c(sqrt(abs(a^2 - c^2)) * complex(1, cos(Arg(c^2 - 
    a^2)/2), sin(Arg(c^2 - a^2)/2)), sqrt(abs(a^2 - c^2)) * complex(1, 
    cos((Arg(c^2 - a^2) + 2 * pi)/2), sin((Arg(c^2 - a^2) + 2 * 
        pi)/2))))
> eval(e, list(a = 2, c = 3))
[1]  2.236068+0i -2.236068+0i
```

I'll close this now, but please let me know whether you can get it to work.

**Comment by wdkrnls** [comment]
Thanks for addressing! I'm excited to give it a try. I don't have easy access to a development environment right now. Do you think you'll be pushing an update to CRAN anytime soon?

**Comment by mikldk** [comment]
I am not sure when the next update will hit CRAN. Hopefully I will be able to submit an update within a month. Would that be useful for you?

**Comment by wdkrnls** [comment]
That sounds just fine for me. Thank you so much for all your efforts!

**Comment by wdkrnls** [comment]
One thing I noticed from the commit fixing things is that there is also no R function called `ceil`. It is `ceiling`.

**Comment by grzegorzmazur** [comment]
Hi,

I've got notifications about both the comment in the code and the issue here. The comment in the code wasn't transformed into an issue, but it still loud and clear :) Thanks a lot, I'll fix it in a minute.

Cheers,
Grzesiek

**Comment by mikldk** [comment]
@wdkrnls : A [new release 1.1.3](https://github.com/r-cas/ryacas/releases/tag/1.1.3) has been submitted to CRAN <https://cran.r-project.org/package=Ryacas> (source version ready, binaries are pending). 

Thanks for finding and reporting the bugs!

**Comment by mikldk** [comment]
@grzegorzmazur : Thanks for fixing these bugs!

**Comment by wdkrnls** [comment]
Works for me! Thanks for providing this great software!
