### ISSUE TITLE
Integration problem

### ISSUE THREAD

**Issue by jiperezga** [r-cas/ryacas#50]
Hello, 

I tried to use the `Ryacas` library to calculate a pair of integrals, and to test the function, I tried to integrate different functions, finding that by setting functions of the form

- x^a * exp(-x)

with a > 1, the result obtained is incorrect.

For example, I used the following code

`library(Ryacas)`
`yac_expr("Integrate(x) x^2* Exp(-(x))")`

the result obtained is

> expression(-2 * exp(-x) - x^2 * exp(-x))

when the real result is 

-  -2 * exp(-x) **- 2 * x * exp(-x)** - x^2 * exp(-x)

where it is observed that the value `- 2 * x * exp(-x)` is omitted.

Due to this I tried using the `caracas` library to replicate the exercise and I got the following result

`library(caracas)`
`sympy <- get_sympy()`
`x <- sympy$symbols('x')`
`fun <- "x**2 * exp(-x)"`
`sympy$integrate(fun, x)`

> (-x**2 - 2*x - 2)*exp(-x)

Which matches with the correct result.

I hope you can give a look to the error that mentioned above since I would like to use the `Ryacas` library to teach my students to solve integrals and derivatives not evaluated in R.

Thank you very much and I look forward to your comments.

**Comment by mikldk** [comment]
Thanks for reporting this. This is probably due to Yacas.

Would it be a possibility to use `[caracas](https://github.com/r-cas/caracas)`? We are developing heavily on it now, see e.g. <https://r-cas.github.io/caracas/articles/introduction.html#integrals>.

**Comment by grzegorzmazur** [comment]
Hi,

Right, it's been a yacas bug. Quick'n'dirty fix is provided in https://github.com/grzegorzmazur/yacas/commit/0225e8e5dcd4308e58cde86c662b09285e6535ed

Please note that for the fix to work it has to be pulled to ryacas.

Cheers,
Grzesiek

**Comment by mikldk** [comment]
Thanks, @grzegorzmazur ! 

This was fixed by cbfb86e7513ef06df31e0d8dd6cd1a496bd1ee1f with tests in 4c92b0f00f11091a8b87cb19f67e87be984aaf2d.

I will close this now, but please let me know if you can get this to work.

**Comment by jiperezga** [comment]
Thanks, @grzegorzmazur and @mikldk 

The problem was corrected.

The integral now gives the correct result.

Thank you again!
