### ISSUE TITLE
sum of a vector in ryacas

### ISSUE THREAD

**Issue by bnicenboim** [r-cas/ryacas#51]
Hi, I've just discovered this package! very cool!

Say that I have a vector of x
```
N <- 20
x <- paste0("x_", 1:N) %>% ysym()
```
I want to sum n even numbers starting from N:

<a href="https://www.codecogs.com/eqnedit.php?latex=\sum_{i=1}^{n}&space;x_{N-2&space;\cdot(i-1)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum_{i=1}^{n}&space;x_{N-2&space;\cdot(i-1)}" title="\sum_{i=1}^{n} x_{N-2 \cdot(i-1)}" /></a>

If I set $n=5$ then I can do it:
```
n <- 5
i <- seq(1,n)
sum(x[N - 2 * (i-1)])
```

But what if I want leave it with an arbitrary $n$?
Is there some way to do this?
Can ryacas use the large sigma to denote summation? I'd like to generate something like the latex code before. Is it possible?

**Comment by bnicenboim** [comment]
I managed to do it in the lower level way
```
paste0("Sum(i,1,n,x[N - 2*i])") %>% yac_str() %>% y_fn("TeXForm") %>% yac_str()
```

but `sum.yac_symbol` has the same arguments, so I should be able to do it somehow...
(It would be good to add an example of sum in the documentation).

**Comment by mikldk** [comment]
Thanks for this. Unfortunately, this is not possible in `Ryacas`, but it is possible in our [`caracas`](https://github.com/r-cas/caracas) package that builds on SymPy: <https://r-cas.github.io/caracas/articles/reference.html#sums>.

**Comment by bnicenboim** [comment]
oh, really? But how do I use the extra arguments of `sum.yac_symbol` ?
Unfortunately, I couldn't make caracas to work yet :/, I'll investigate what's happening and I might open an issue.

Would you say that caracas is more complete/works better than Ryacas?

**Comment by mikldk** [comment]
You can do something like this:

``` r
library(Ryacas)
s <- yac_symbol("Sum(i,1,n,x[N - 2*i])")
s
#> y: Sum(i,1,n,x[N-2*i])
tex(s)
#> [1] "\\sum _{i = 1} ^{n} x _{N - 2 i}"
as.character(s)
#> [1] "Sum(i,1,n,x[N-2*i])"
```
Please let us know if you cannot get it working -- or if you had to do something that was not documented.

The packages use different back-ends (yacas/SymPy) that are different in themselves. In the future we probably will spend most development time on `caracas`.
