### ISSUE TITLE
conflicts with base r functions

### ISSUE THREAD

**Issue by XiangyunHuang** [r-cas/ryacas#53]
When I load Ryacas package, it conflicts with base R's functions

```r
library(Ryacas)

Attaching package: 'Ryacas'

The following object is masked from 'package:stats':

    integrate

The following objects are masked from 'package:base':

    %*%, diag, diag<-, lower.tri, upper.tri

> conflicts()
[1] "integrate" "%*%"       "body<-"    "diag"      "diag<-"    "kronecker" "lower.tri" "plot"      "upper.tri"
```

I don't think it's also good idea like dplyr

**Comment by mikldk** [comment]
Thanks for this. It is not ideal, but sometimes it is very difficult to avoid, e.g. for `diag()` that is not born as a generic, but should also work for symbolic matrices.
