### ISSUE TITLE
vec and vech

### ISSUE THREAD

**Issue by jeksterslab** [r-cas/ryacas#57]
I am thinking of adding `vec` and `vech` in `linalg` as these come up from time to time in my work. From my reading of the reference manual however, I am not sure if `yacas` supports vectorization and half-vectorization out of the box. If there's a way to do `vec` and `vech` in `yacas` I'll work on this next. If there's no way to do `vec` and `vech` in `yacas` out of the box, I think it's a good feature request.

What do you think @mikldk @grzegorzmazur ?

https://en.wikipedia.org/wiki/Vectorization_(mathematics)

**Comment by grzegorzmazur** [comment]
Hi,

There's no explicit support for vectorization in yacas, but it can be relatively easily achieved with
```
"Concat" @ Transpose(A)
```
operation. (Matrices are represented as lists of rows, so transpose gives a list of columns which are then glued together.)

Half-vectorization would require more than a single-liner. And perhaps adding duplication and elimination matrices would make sence when we're at this.

Obviously, I always gladly accept pull requests :) If however this is something you need and you are not sure if you can done it in 10 minutes, let me know and I'll add it.

Cheers,
Grzesiek

**Comment by jeksterslab** [comment]
Hi @grzegorzmazur,

I think it would take me more than 10 minutes to implement half-vectorization in `yacas` as my familiarity with the code base is not as good as my familiarity with the `Ryacas` code base. I'll study `yacas` some more so I can contribute in the future. For now, I would appreciate it if you add this feature.

Best,

Jek

**Comment by grzegorzmazur** [comment]
OK, I've sketched out vectorization and half-vectorization in https://github.com/grzegorzmazur/yacas/commit/84752733ca751be78c4552833cb4c41ff92a27a6
Now it's only getting this over to ryacas, hopefully Mike will help :)

Cheers,
Grzesiek

**Comment by mikldk** [comment]
I have now updated the internal `yacas` to the newest commit (1.9.2 dev) in d1c2d7d1c223240e9b7f268f382009b057836b38. Thus, `Vectorize` and `HalfVectorize` should now be available.

**Comment by jeksterslab** [comment]
Awesome! I'll work on this.

**Comment by jeksterslab** [comment]
For the symmetric matrix

```
1  2  3
2  4  5
3  5  6
```

The half-vectorization should be {1, 2, 3, 4, 5, 6} right? I am assuming that the operation vectorizes the lower triangular elements by column. However, `yacas` returns {1, 2, 4, 3, 5, 6}.

**Comment by grzegorzmazur** [comment]
Right, sorry for silly mistake. Should be fixed in https://github.com/grzegorzmazur/yacas/commit/bc9ea11a90379fccbc1b18d5d069554289183b0c

**Comment by jeksterslab** [comment]
Thanks @grzegorzmazur . `vec` and `vech` tests should pass when the `yacas` code in `Ryacas` gets updated.

**Comment by mikldk** [comment]
@jeksterslab can you verify that it now works?

**Comment by jeksterslab** [comment]
All the tests are passing.

**Comment by jeksterslab** [comment]
The last pull request closes this issue.
