### ISSUE TITLE
Solving an equality doesn't work with powers of ten by the degree of 11 or so

### ISSUE THREAD

**Issue by piiskop** [r-cas/ryacas#61]
My code:

`MASS_PROTON = 1.6726219e-27
ELEMENTARYCHARGE = 1.6E-19
library(Ryacas)
equality = paste(MASS_PROTON * 35e6 ^ 2, "/ radius ==", ELEMENTARYCHARGE * 35e6 * .5 * sin(pi / 2), sep = " ")
equality
radiusOfProton = eval(parse(text = yac_str(y_rmvars(paste("Solve(", equation, ", radius)", sep = "")))))
`
The result:

> Error in eval(parse(text = yac_str(y_rmvars(paste("Solve(", equation,  : 
  object 'Undefined' not found
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> eval -> eval
Execution halted

The solver should recognize that it's possible to cancel out some degrees of ten before trying to do a calculation with a large or very zero-close number. If I perfom the calculation manually:

` 2.0489618275e-12 / 2.8e-12`

then I see the correct result:

> [1] 0.7317721

**Comment by mikldk** [comment]
@piiskop Thanks for reporting this. Not sure why Yacas cannot solve it.

But the [`caracas`](https://cran.r-project.org/package=caracas) package can help you:

``` r
library(caracas)

def_sym(mp, ec, r)

lhs <- mp * 35e6^2 / r
rhs <- ec * 35e6 / 2

sol <- solve_sys(lhs, rhs, r)
sol
#> Solution 1:
#>   r =  70000000.0⋅mp
#>       ─────────────
#>             ec

sol_r <- sol[[1]]$r
sol_r
#> [caracas]: 70000000.0⋅mp
#>            ─────────────
#>                  ec

MASS_PROTON <- 1.6726219e-27 
ELEMENTARYCHARGE <- 1.6e-19 
eval(as_expr(sol_r), list(mp = MASS_PROTON, ec = ELEMENTARYCHARGE))
#> [1] 0.7317721
```

**Comment by mikldk** [comment]
@piiskop I would suggest trying to report this with a MWE made in Python to [SymPy](https://github.com/sympy/sympy) as it is probably due to their solvers. Please mention this issue. I am closing this issue.
