### ISSUE TITLE
How to connect yacas with rstudio

### ISSUE THREAD

**Issue by esther1262** [r-cas/ryacas#62]
Hi,
I already downloaded Yacas on my windows. I first installed package Ryacas directly from Rstudio but no yacas functions can be run. 
I later ran this command and got the following errors:

```
> devtools::install_github("r-cas/ryacas", build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo r-cas/ryacas@HEAD
√  checking for file 'C:\Users\Esther\AppData\Local\Temp\RtmpEpL65w\remotes58d46bf01207\r-cas-ryacas-ea52235/DESCRIPTION' (684ms)
-  preparing 'Ryacas': (1.4s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1s)
-  checking for empty or unneeded directories (501ms)
-  building 'Ryacas_1.1.3.9002.tar.gz'
   
Installing package into ‘C:/Users/Esther/Documents/R/win-library/4.1’ as ‘lib’ is unspecified)
* installing *source* package 'Ryacas' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Users/Esther/Documents/R/win-library/4.1/Ryacas'
* restoring previous 'C:/Users/Esther/Documents/R/win-library/4.1/Ryacas'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\Esther\Documents\R\win-library\4.1\00LOCK-Ryacas\Ryacas\libs\x64\Ryacas.dll to C:\Users\Esther\Documents\R\win-library\4.1\Ryacas\libs\x64\Ryacas.dll: Permission denied
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/ESTHER~1/AppData/Local/Temp/RtmpEpL65w/file58d4192555cc/Ryacas_1.1.3.9002.tar.gz’ had non-zero exit status
```

How to run/install ryacas?

Thanks

**Comment by mikldk** [comment]
@esther1262 Would you be willing to contribute with your solution (if others stumble across the same problem it might help them)?

**Comment by ggrothendieck** [comment]
It was also posted and resolve on SO.  It seems it was a combination of a bad R install and use of outdated documentation. https://stackoverflow.com/questions/71279994/unable-to-install-yacas-with-rstudio

**Comment by esther1262** [comment]
I think R’s installation wasnt a problem. There are two ryacas packages, one for the old commands. I didn’t install the old version. Also in R, we have to do something like yacas(“function”) instead of calling the function directly. I am struggling on how to use it with r interface but I’m think I’m on the right track.

**Comment by mikldk** [comment]
> I think R’s installation wasnt a problem. There are two ryacas packages, one for the old commands. I didn’t install the old version. Also in R, we have to do something like yacas(“function”) instead of calling the function directly. I am still struggling on how to use it with r interface but I think I’m on the right track.

Have you read the "Getting started" vignette: <https://cran.r-project.org/web/packages/Ryacas/vignettes/getting-started.html>? There are more vignettes available from <https://cran.r-project.org/package=Ryacas>.

**Comment by esther1262** [comment]
Yes I later did. Thanks. There were many references when I googled. I got messed up a little. (I actually have some coding questions,  I will ask in a separate issue. )
