### ISSUE TITLE
Ryacas::simplify() does not always find most simple representation in first run

### ISSUE THREAD

**Issue by FBrockmeyer** [r-cas/ryacas#69]
This is a feature request.

I recently dabbled into `{Ryacas}` and enjoyed implementing  `Ryacas::simplify()` in some projects. 
However, I noticed that `Ryacas::simplify()` sometimes fails to find the most simple representation of an expression, at least from an human perspective. Here is a reprex: 

```r-lang 
> chr = "3*x^2/x^4-x^3*(4 *x^3)/(x^4)^2"
> rchr = Ryacas::ysym(chr)
> Ryacas::simplify(rchr)
y: (-x^10)/x^12
> Ryacas::simplify(rchr) |> Ryacas::simplify()
y: (-1)/x^2
```
As we can see, a second execution finds a more simple representation. 

Therefore, I suggest to add a `while`-routine  

```r-lang 
> simplify2 = \(x) { 
+   repeat {
+     o = x 
+     x = Ryacas::simplify(x)
+     if(as.character(o) == as.character(x)) break
+   }
+   x
+ }
> simplify2(rchr)
y: (-1)/x^2
```
which, obviously, should be supplemented with a second condition preventing the function from running permanently in some (rare) edge cases.

**Comment by hojsgaard** [comment]
My understanding is that simplify() in yacas (as well as in sympy which is interfaced with the caracas package) is very heuristic and sometimes running simplify() can be rather time consuming. Perhaps it is better to leave it as it is.
Best
Søren
